### ISSUE TITLE
[BUG] NameError: name 'I' is not defined

### ISSUE THREAD

**Issue by saloniamatteo** [fakefred/memethesis-cli#3]
I got this error while trying to save the image:
`
Save meme to: (only .jpg supported)  test.jpg         Traceback (most recent call last):                        File "/data/data/com.termux/files/usr/bin/memethesis", line 8, in <module>                                        sys.exit(main())                                      File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/memethesis/__main__.py", line 64, in main       interactive()                                         File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/memethesis/interactive.py", line 235, in interactive                                                    path = ((o if search('\.(jpe?g|png)$', o, flags=I) else o + '.jpg')                                         NameError: name 'I' is not defined
`

**Comment by fakefred** [comment]
Which version of Python are you using? @mrbesen encountered the exact same problem in #1.

**Comment by saloniamatteo** [comment]
> Which version of Python are you using? @mrbesen encountered the exact same problem in #1.

Python 3.8

**Comment by fakefred** [comment]
To solve the problem, use the git version instead of that from pypi. Run `python setup.py bdist_wheel`, `cd dist`, and `pip install memethesis-<something>.whl`. I'll update the pypi version soon.

**Comment by saloniamatteo** [comment]
Thank you very much :)

**Comment by saloniamatteo** [comment]
![finally](https://user-images.githubusercontent.com/28765699/74154970-fb27ca80-4c13-11ea-926e-272b62e94643.png)
I had some problems installing it, but I thankfully installed it after a LOOONG time \*phew\*

I made the image above using memethesis by the way. It's really awesome! Please add more meme templates!

**Comment by fakefred** [comment]
Yes, pypi is painfully inconsiderate when I want to upgrade packages. It is best to keep doing `pip install memethesis==2.1.1` until it surrenders and does as intended.
