### ISSUE TITLE
Vim key bindings in interactive mode

### ISSUE THREAD

**Issue by Awerito** [fakefred/memethesis-cli#7]
Add simple ones like <h, j, k, l> like arrow keys.

**Comment by fakefred** [comment]
This is out of scope of this project, for this is an issue of its dependency `PyInquirer`. However, I am willing to look into it and solve a few other problems for once and for all.

**Comment by fakefred** [comment]
(In fact I find only j and k useful here)

**Comment by fakefred** [comment]
Sorry, the deps don't seem to support such keys well. If you find arrow keys too tedious to reach, I could add an option to enable selection with number keys.

**Comment by Awerito** [comment]
Nah, the repo is already excellent. If that can't be done is ok.
