### ISSUE TITLE
[GITHUB FEATURE REQUEST] Change the wheel's release name on GitHub 

### ISSUE THREAD

**Issue by saloniamatteo** [fakefred/memethesis-cli#9]
You should change the name of the built wheel starting now, including newer versions, to a static name, like "memethesis.whl". I wanted to add to the README a way to install the package wheel directly, using this URL: https://github.com/fakefred/memethesis-cli/releases/download/latest/memethesis.whl
So this way it's a more direct approach to install memethesis.

**Comment by fakefred** [comment]
Okay, I guess? A pypi release ships with a GitHub one which provides a static name, but I'll take your advice.

________________________________
